# Generated by Django 4.2 on 2023-05-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_id_hub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id_hub',
            name='CAP',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='id_hub',
            name='HT',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
